# Change these first
owner: wiktorwojcik112 # Your GitHub username
repo: WWUpptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Personal page
    url: https://wiktor.thedev.id
  - name: Extiri
    url: https://extiri.com
  - name: Word of Day API
    url: https://wiktorwojcik.eu.pythonanywhere.com/word-of-day
  - name: Extiri API
    url: https://extiri.com/api/1/snippets

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /WWUpptime
  logoUrl: https://wiktor.thedev.id/Images/profile.png
  name: WWUpptime
  introTitle: "Status page"
  introMessage: This page is showing status of my services and site. It is powered by [Upptime](https://github.com/upptime/upptime). 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
